version: '3.8'

services:
  parse:
    container_name: "parse-service"
    image: ghcr.io/teamverdeingsis/parse:latest
    ports:
      - 8081:8080
    environment:
      DB_HOST: db_parse
      DB_PORT: 5432
      DB_NAME: parse-db
      DB_USER: sa
      DB_PASSWORD: password
    depends_on:
      - db_parse
    networks:
      - app-network

  permission:
    container_name: "permission-service"
    image: ghcr.io/teamverdeingsis/permissions:latest
    ports:
      - 8082:8080
    environment:
      DB_HOST: db_permission
      DB_PORT: 5432
      DB_NAME: permission-db
      DB_USER: sa
      DB_PASSWORD: password
    depends_on:
      - db_permission
    networks:
      - app-network

  snippets:
    container_name: "snippets-service"
    image: ghcr.io/teamverdeingsis/snippets:latest
    ports:
      - 8083:8080
    environment:
      DB_HOST: db_snippets
      DB_PORT: 5432
      DB_NAME: snippets-db
      DB_USER: sa
      DB_PASSWORD: password
      auth0.audience: https://snippets-api
    depends_on:
      - db_snippets
      - parse
      - permission
    networks:
      - app-network

  db_permission:
    container_name: db_permission
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: permission-db
    volumes:
      - pgdata_permission:/var/lib/postgresql/data
    networks:
      - app-network

  db_snippets:
    container_name: db_snippets
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snippets-db
    volumes:
      - pgdata_snippets:/var/lib/postgresql/data
    networks:
      - app-network

  db_parse:
    container_name: db_parse
    image: postgres:12
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parse-db
    volumes:
      - pgdata_parse:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata_permission:
  pgdata_snippets:
  pgdata_parse:

networks:
  app-network:
    driver: bridge
