name: Update Infra Services

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update-infra]

jobs:
  update-infra:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Update Services
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/your_user/infra
            docker-compose pull
            docker-compose up -d
