name: Update Infra Services

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update-infra]

jobs:
  update-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH Key file
        run: |
          echo "${{ secrets.VM_SSH_KEY }}" > /tmp/vm_ssh_key
          chmod 600 /tmp/vm_ssh_key  # Permisos de solo lectura

      - name: SSH and Update Services
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/vm_ssh_key ${{ vars.VM_USER }}@${{ vars.VM_HOST }} "cd /home/teamVerde1/infra && sudo docker compose down && sudo docker compose up -d"

      - name: Remove SSH Key file
        run: |
          rm -f /tmp/vm_ssh_key  
