name: Update Infra Services

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update-infra]

jobs:
  update-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: SSH and Update Services
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "cd /home/teamVerde1/infra && docker-compose pull && docker-compose up -d"
